package com.shopai.agent.engine;

import java.util.List;

/** A structured plan generated by the LLM, containing an ordered list of steps. */
public record ExecutionPlan(List<PlanStep> steps) {

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ExecutionPlan[\n");
        for (PlanStep s : steps) {
            sb.append("  ").append(s).append("\n");
        }
        return sb.append("]").toString();
    }
}
